# Generated by Django 4.2.26 on 2025-12-02 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='게시글 제목', max_length=200)),
                ('content', models.TextField(help_text='게시글 내용')),
                ('view_count', models.IntegerField(default=0, help_text='조회수')),
                ('like_count', models.IntegerField(default=0, help_text='좋아요 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부 (소프트 삭제)')),
                ('user', models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '커뮤니티 게시글',
                'verbose_name_plural': '커뮤니티 게시글 목록',
                'db_table': 'community_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부 (소프트 삭제)')),
                ('post', models.ForeignKey(help_text='게시글', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost')),
                ('user', models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '커뮤니티 댓글',
                'verbose_name_plural': '커뮤니티 댓글 목록',
                'db_table': 'community_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
