# Generated by Django 4.2.27 on 2025-12-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communitypostlike'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitypostlike',
            new_name='community_p_post_id_4541d9_idx',
            old_name='community__post_id_user_idx',
        ),
    ]
