# Generated by Django 4.2.26 on 2025-12-02 02:26

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='이메일 주소 (로그인 ID)', max_length=254, unique=True)),
                ('google_id', models.CharField(blank=True, help_text='Google OAuth Provider Account ID', max_length=255, null=True, unique=True)),
                ('profile_image', models.URLField(blank=True, help_text='Google 프로필 이미지 URL', max_length=500, null=True)),
                ('is_new_user', models.BooleanField(default=True, help_text='신규 사용자 여부 (첫 로그인 시 True)')),
                ('survey_completed', models.BooleanField(default=False, help_text='선호도 설문 완료 여부')),
                ('job_type', models.CharField(blank=True, choices=[('직장인', '직장인'), ('학생', '학생'), ('취준생', '취준생'), ('프리랜서', '프리랜서'), ('자영업', '자영업')], help_text='직업 유형', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='마지막 수정 시간')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorities', models.JSONField(help_text='선호도 우선순위 JSON (예: {주변공원: 1, 편의시설: 2})')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='설문 응답 시간')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='preference_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '선호도 설문',
                'verbose_name_plural': '선호도 설문 목록',
                'db_table': 'preference_surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(help_text='매물 ID', max_length=255)),
                ('action', models.CharField(choices=[('add', '추가'), ('remove', '삭제')], help_text='행동 유형', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='발생 시간')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '찜 목록 이력',
                'verbose_name_plural': '찜 목록 이력 목록',
                'db_table': 'wishlist_histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wishlist_hi_user_id_35efb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(help_text='매물 ID', max_length=255)),
                ('memo', models.TextField(blank=True, help_text='사용자 메모', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='찜한 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '찜 목록',
                'verbose_name_plural': '찜 목록',
                'db_table': 'wishlists',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'listing_id')},
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_conditions', models.JSONField(help_text='검색 조건 JSON (예: {region, price_min, price_max, room_type})')),
                ('result_count', models.IntegerField(default=0, help_text='검색 결과 개수')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='검색 시간')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '검색 이력',
                'verbose_name_plural': '검색 이력 목록',
                'db_table': 'search_histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_hist_user_id_e2e21f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '로그인'), ('logout', '로그아웃')], help_text='행동 유형', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='접속 IP 주소', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='브라우저 User-Agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '로그인 이력',
                'verbose_name_plural': '로그인 이력 목록',
                'db_table': 'login_histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='login_histo_user_id_ca7b6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListingViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(help_text='매물 ID', max_length=255)),
                ('view_duration', models.IntegerField(blank=True, help_text='조회 시간(초)', null=True)),
                ('scroll_depth', models.IntegerField(blank=True, help_text='스크롤 깊이(%)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='조회 시간')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='listing_view_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '매물 조회 이력',
                'verbose_name_plural': '매물 조회 이력 목록',
                'db_table': 'listing_view_histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='listing_vie_user_id_0006c3_idx'), models.Index(fields=['listing_id'], name='listing_vie_listing_9678ce_idx')],
            },
        ),
    ]
