# Generated by Django 4.2.26 on 2025-12-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_file',
            field=models.ImageField(blank=True, help_text='사용자가 업로드한 프로필 이미지', null=True, upload_to='profile_images/'),
        ),
    ]
