# Generated by Django 4.2.27 on 2025-12-23 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_image_file_user_profile_image_mime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingviewhistory',
            options={'ordering': ['-last_viewed_at'], 'verbose_name': '매물 조회 이력', 'verbose_name_plural': '매물 조회 이력 목록'},
        ),
        migrations.RemoveIndex(
            model_name='listingviewhistory',
            name='listing_vie_user_id_0006c3_idx',
        ),
        migrations.AddField(
            model_name='listingviewhistory',
            name='first_viewed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='최초 조회 시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingviewhistory',
            name='last_viewed_at',
            field=models.DateTimeField(auto_now=True, help_text='마지막 조회 시간'),
        ),
        migrations.AddField(
            model_name='listingviewhistory',
            name='max_scroll_depth',
            field=models.IntegerField(default=0, help_text='최대 스크롤 깊이(%) - 가장 깊게 본 기록'),
        ),
        migrations.AddField(
            model_name='listingviewhistory',
            name='total_view_duration',
            field=models.IntegerField(default=0, help_text='총 조회 시간(초) - 누적'),
        ),
        migrations.AddField(
            model_name='listingviewhistory',
            name='view_count',
            field=models.IntegerField(default=1, help_text='조회 횟수 (재방문 빈도)'),
        ),
        migrations.AlterUniqueTogether(
            name='listingviewhistory',
            unique_together={('user', 'listing_id')},
        ),
        migrations.AddIndex(
            model_name='listingviewhistory',
            index=models.Index(fields=['user', '-last_viewed_at'], name='listing_vie_user_id_cbaa50_idx'),
        ),
        migrations.AddIndex(
            model_name='listingviewhistory',
            index=models.Index(fields=['user', '-view_count'], name='listing_vie_user_id_c38049_idx'),
        ),
        migrations.AddIndex(
            model_name='listingviewhistory',
            index=models.Index(fields=['user', '-total_view_duration'], name='listing_vie_user_id_665fb0_idx'),
        ),
        migrations.RemoveField(
            model_name='listingviewhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listingviewhistory',
            name='scroll_depth',
        ),
        migrations.RemoveField(
            model_name='listingviewhistory',
            name='view_duration',
        ),
    ]
