# Generated by Django 4.2.27 on 2025-12-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersearchlog',
            new_name='user_search_created_ddb35c_idx',
            old_name='user_search_created_a_e8f3c5_idx',
        ),
        migrations.RenameIndex(
            model_name='usersearchlog',
            new_name='user_search_query_3fff1f_idx',
            old_name='user_search_query_7e8d4a_idx',
        ),
        migrations.RenameIndex(
            model_name='usersearchlog',
            new_name='user_search_session_1d5a7e_idx',
            old_name='user_search_session_3b9f2c_idx',
        ),
    ]
