"""
월세 데이터 분석 및 예측 모델 패키지
"""
__version__ = "1.0.0"

from .data_preprocessing import (
    load_data,
    filter_walse_data,
    drop_unnecessary_columns,
    remove_invalid_room_data,
    remove_null_dong,
    preprocess_data
)

from .feature_engineering import (
    parse_korean_money,
    split_deposit_rent,
    calculate_converted_deposit,
    extract_management_fee,
    add_management_fee,
    extract_area,
    convert_to_pyeong_from_raw,
    add_area_features,
    building_usage_score,
    building_type_score,
    add_building_features,
    extract_floor_info,
    add_floor_feature,
    parse_room_toilet,
    add_room_features,
    room_living_score,
    add_room_living_feature,
    direction_score,
    add_direction_feature,
    convert_parking,
    add_parking_feature,
    convert_violation,
    add_violation_feature,
    extract_gu_dong,
    add_location_features,
    parse_desc_keywords,
    parse_life_options,
    clean_unified_options,
    merge_lists,
    add_option_features,
    create_all_features,
    prepare_ml_features
)

from .model import (
    split_data,
    create_model,
    is_fitted_model,
    train_model,
    predict_model,
    evaluate_model,
    print_evaluation_results,
    create_comparison_dataframe,
    full_train_and_evaluate,
    save_model,
    load_model,
    save_predictions,
    save_metrics
)

from .visualization import (
    setup_matplotlib_korean,
    set_matplotlib_backend,
    plot_correlation_heatmap,
    plot_top_correlation_heatmap,
    plot_feature_vs_target_regplot,
    plot_numerical_boxplots,
    plot_target_distribution,
    plot_log_target_distribution,
    plot_area_vs_target_by_floor,
    plot_price_per_pyeong_vs_target,
    plot_rooms_vs_target_boxplot,
    plot_error_rate_histogram,
    plot_error_rate_boxplot,
    plot_actual_vs_predicted,
    initialize_shap,
    create_shap_explainer,
    plot_shap_summary_bar,
    plot_shap_summary,
    plot_shap_force,
    plot_all_eda,
    plot_model_results,
    plot_shap_analysis,
    save_figure,
    save_all_eda_plots,
    save_model_result_plots
)

from .predict import (
    predict_single_property,
    evaluate_price_difference,
    predict_and_evaluate_properties,
    analyze_price_distribution,
    save_prediction_results,
    get_cheap_properties,
    get_expensive_properties
)

__all__ = [
    # data_preprocessing
    "load_data",
    "filter_walse_data",
    "drop_unnecessary_columns",
    "remove_invalid_room_data",
    "remove_null_dong",
    "preprocess_data",
    # feature_engineering
    "parse_korean_money",
    "split_deposit_rent",
    "calculate_converted_deposit",
    "extract_management_fee",
    "add_management_fee",
    "extract_area",
    "convert_to_pyeong_from_raw",
    "add_area_features",
    "building_usage_score",
    "building_type_score",
    "add_building_features",
    "extract_floor_info",
    "add_floor_feature",
    "parse_room_toilet",
    "add_room_features",
    "room_living_score",
    "add_room_living_feature",
    "direction_score",
    "add_direction_feature",
    "convert_parking",
    "add_parking_feature",
    "convert_violation",
    "add_violation_feature",
    "extract_gu_dong",
    "add_location_features",
    "parse_desc_keywords",
    "parse_life_options",
    "clean_unified_options",
    "merge_lists",
    "add_option_features",
    "create_all_features",
    "prepare_ml_features",
    # model
    "split_data",
    "create_model",
    "is_fitted_model",
    "train_model",
    "predict_model",
    "evaluate_model",
    "print_evaluation_results",
    "create_comparison_dataframe",
    "full_train_and_evaluate",
    "save_model",
    "load_model",
    "save_predictions",
    "save_metrics",
    # visualization
    "setup_matplotlib_korean",
    "set_matplotlib_backend",
    "plot_correlation_heatmap",
    "plot_top_correlation_heatmap",
    "plot_feature_vs_target_regplot",
    "plot_numerical_boxplots",
    "plot_target_distribution",
    "plot_log_target_distribution",
    "plot_area_vs_target_by_floor",
    "plot_price_per_pyeong_vs_target",
    "plot_rooms_vs_target_boxplot",
    "plot_error_rate_histogram",
    "plot_error_rate_boxplot",
    "plot_actual_vs_predicted",
    "initialize_shap",
    "create_shap_explainer",
    "plot_shap_summary_bar",
    "plot_shap_summary",
    "plot_shap_force",
    "plot_all_eda",
    "plot_model_results",
    "plot_shap_analysis",
    "save_figure",
    "save_all_eda_plots",
    "save_model_result_plots",
    # predict
    "predict_single_property",
    "evaluate_price_difference",
    "predict_and_evaluate_properties",
    "analyze_price_distribution",
    "save_prediction_results",
    "get_cheap_properties",
    "get_expensive_properties",
]
