# Generated by Django 4.2.27 on 2025-12-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('land_id', models.AutoField(primary_key=True, serialize=False)),
                ('land_num', models.CharField(max_length=20, unique=True)),
                ('building_type', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('view_count', models.IntegerField(blank=True, default=0, null=True)),
                ('deal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('deposit', models.IntegerField(blank=True, default=0, null=True)),
                ('monthly_rent', models.IntegerField(blank=True, default=0, null=True)),
                ('jeonse_price', models.IntegerField(blank=True, default=0, null=True)),
                ('sale_price', models.IntegerField(blank=True, default=0, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('trade_info', models.JSONField(blank=True, null=True)),
                ('listing_info', models.JSONField(blank=True, null=True)),
                ('additional_options', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'land',
                'ordering': ['-land_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandBroker',
            fields=[
                ('landbroker_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(blank=True, help_text='중개사명', max_length=200, null=True)),
                ('representative', models.CharField(blank=True, help_text='대표자', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, help_text='전화번호', max_length=50, null=True)),
                ('address', models.CharField(blank=True, help_text='주소', max_length=500, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='등록번호 (고유키)', max_length=100, null=True, unique=True)),
                ('completed_deals', models.IntegerField(default=0, help_text='거래완료')),
                ('registered_properties', models.IntegerField(default=0, help_text='등록매물')),
                ('brokers_count', models.IntegerField(default=0, help_text='공인중개사수')),
                ('assistants_count', models.IntegerField(default=0, help_text='중개보조원수')),
                ('staff_count', models.IntegerField(default=0, help_text='일반직원수')),
                ('region', models.CharField(blank=True, help_text='지역명 (시군구)', max_length=100, null=True)),
                ('registration_date', models.DateField(blank=True, help_text='등록일', null=True)),
                ('trust_score', models.CharField(blank=True, choices=[('A', 'A등급 (우수)'), ('B', 'B등급 (보통)'), ('C', 'C등급 (주의)')], help_text='AI 모델 예측 신뢰도 등급', max_length=1, null=True)),
                ('trust_score_updated_at', models.DateTimeField(blank=True, help_text='신뢰도 점수 마지막 업데이트 시각', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'landbroker',
                'ordering': ['-landbroker_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('landimage_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'land_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceClassificationResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('land_num', models.CharField(db_column='매물번호', max_length=20, unique=True)),
                ('land_url', models.TextField(blank=True, db_column='매물_url', null=True)),
                ('prediction_class', models.IntegerField(db_column='예측_클래스', help_text='예측 클래스 (0: 저렴, 1: 적정, 2: 비쌈)')),
                ('prediction_label', models.CharField(db_column='예측_레이블', help_text='예측 레이블 (영문)', max_length=50)),
                ('prediction_label_korean', models.CharField(db_column='예측_레이블_한글', help_text='예측 레이블 (한글)', max_length=50)),
                ('probability_underpriced', models.FloatField(db_column='저렴_확률', help_text='저렴 확률')),
                ('probability_fair', models.FloatField(db_column='적정_확률', help_text='적정 확률')),
                ('probability_overpriced', models.FloatField(db_column='비쌈_확률', help_text='비쌈 확률')),
                ('prediction_datetime', models.DateTimeField(blank=True, db_column='예측_일시', null=True)),
            ],
            options={
                'db_table': 'price_classification_results',
                'managed': False,
            },
        ),
    ]
